services:
    adguard: #service 1
        image: adguard/adguardhome
        container_name: veilnet/adguard

        ports:                  # hostport:containerport/
            - "53:53/tcp"       # port 53 host used for DNS, just match to container
            - "53:53/udp"
            - "3000:3000"
        volumes:
            - ./configs/adguard/work:/opt/adguardhome/work
            - ./configs/adguard/conf:/opt/adguard/conf
        restart: unless-stopped